CREATE TABLE IF NOT EXISTS "orders" (id SERIAL PRIMARY KEY, user_id INT NOT NULL, json VARCHAR(1024) NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS "users" (id SERIAL PRIMARY KEY, username VARCHAR(256) NOT NULL, password VARCHAR(256) NOT NULL, email VARCHAR(256) NOT NULL, admin BOOLEAN DEFAULT false);
